### ISSUE TITLE
constants_pattern only matches integers

### ISSUE THREAD

**Issue by maormann** [maormann/PARLEY#1]
The comment says `# get all constants`
but the regex constants_pattern only matches integers.
https://github.com/maormann/PARLEY/blob/1747bf4d747cd481c19cdceeb8e4ebd689e118f2/umc_synthesis.py#L25

Should double and booleans also be matched?

btw. booleans will not work at this moment, because evochecker can't porcess booleans right now.
See [here](https://github.com/gerasimou/EvoChecker/issues/4)

**Comment by carwehlm** [comment]
Thanks for the comment, you're completely right. All constants should be matched here, otherwise there might be a problem when they are used in the model.

**Comment by maormann** [comment]
I took a closer look at the get_variables function. It looks to me like the constants are only used to set the limits for integer variable declarations if they are set by constants.

So collecting integer variables should be sufficient.

However, integers in Prism can also be negative, so I will extend the regular expressions here.

Another thing I noticed is that the initialization of variables can also be done by the [init construct](https://www.prismmodelchecker.org/manual/ThePRISMLanguage/MultipleInitialStates). However, including this would increase the complexity unnecessarily. But we should probably point out this limitation.

**Comment by carwehlm** [comment]
Indeed. But can't bool variables be set to const bools initially? 
Good point regarding negative values there!

**Comment by carwehlm** [comment]
> Indeed. But can't bool variables be set to const bools initially? Good point regarding negative values there!

Sorry, I meant doubles. Can't doubles be set to const doubles initially? 
Same is true for bools, as well, though.

**Comment by maormann** [comment]
PRISM only supports integers and Booleans as module variables. So we don't need to worry about doubles for declarations.

**Comment by carwehlm** [comment]
Ah great, thanks!

**Comment by maormann** [comment]
But here is the last thing. Const can be expressions. So
```
const int a = 1;
const int b = 2;
const int c = a + b;
```
is possible.
Currently we would miss const c.

Is there a way to build a PRISM Model and read the information elsewhere?

**Comment by carwehlm** [comment]
For the sake of this work, I think we can require that the bounds and initial values are set to concrete integer values or to something following the regEx we have (with the addition of negative integers maybe) 
In the end, this requirement is not hindering the model in any way here. A simple script could easily resolve any use of variables in these cases and grab the concrete value instead and re-write the model accordingly. What do you think?

**Comment by maormann** [comment]
Yes, that's okay for me.
I've now looked again at what PRISM offers and found a switch called 
`-exportprismconst`. But strangely enough, it doesn't work for me.

```
-exportprismconst <file> ....... Export final PRISM model with expanded constants to a file
```

**Comment by maormann** [comment]
Okay figured it out.
`-exportprismconst` only works, when an undefined constant exists. But will replace it then in-place.
Too bad, that would certainly have made things easier.

**Comment by maormann** [comment]
Okay [this Commit](https://github.com/maormann/PARLEY/commit/dd4407138dd44b3eec6693acedc30bc4fa4238ec) should do the trick.
The RegEx could be a little easier, if we use prism to export the model with the `-exportprism` switch. But I see this as optional.

**Comment by carwehlm** [comment]
Yes looks good!
